version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ai_data:/app/server/data
    restart: unless-stopped

volumes:
  ai_data:
