name: Scheduled Web Scraping

on:
  schedule:
    # Run twice daily at 8AM and 8PM UTC
    - cron: '0 8,20 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Full git history is needed to get proper commit timestamps 
          fetch-depth: 0
      
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run scraper
        run: npm run scrape
      
      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add server/data/
          timestamp=$(date -u)
          git commit -m "Automated data update: ${timestamp}" || exit 0
          git push
